### ISSUE TITLE
Windows 7 - ImportError: No module named 'version” when importing SOAPpy

### ISSUE THREAD

**Issue by starnav** [dyve/django-bootstrap-toolkit#114]
I have been using **python 3.4** on **windows 7** for my project and have installed **SOAPpy 0.12.22** successfully. 
Now, I am getting an error message “ImportError: No module named 'version” when importing SOAPpy.
 
Can someone help me to fix this issue on windows 7? Thanks. 

here is 
`C:\>where python
C:\Python34\python.exe

C:\>python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import SOAPpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python34\lib\site-packages\soappy-0.12.22-py3.4.egg\SOAPpy\__init__.py", line 3, in <module>
**ImportError: No module named 'version'**
>>>`

**Comment by starnav** [comment]
All right. I found the problem. 

I found the associated package for Python 34. I have installed SOAPpy-py3-0.52.24. No issues now. 

Thanks.
